package registry

// Resource is a parsed Kubernetes resource with its raw fields and provenance.
type Resource struct {
	APIVersion string
	Kind       string
	Name       string
	Namespace  string
	Raw        map[string]interface{}

	// Source is the file this resource was loaded from (empty for synthetic resources).
	SourceFile string
	// Inline is true when this resource was extracted from a ResourceSet.spec.resources list.
	Inline bool
	// Synthetic is true when this resource was generated by a Synthesizer rule.
	Synthetic bool
	// SyntheticFrom points to the resource that triggered synthesis.
	SyntheticFrom *ResourceRef
	// InputContext holds the ResourceSet input values used to materialize this resource.
	InputContext map[string]interface{}
}

// ResourceRef is a lightweight pointer to a resource by kind/namespace/name.
type ResourceRef struct {
	Kind      string
	Namespace string
	Name      string
	File      string
}

// Artifact is a discovered OCI reference with its full resolution chain.
type Artifact struct {
	// FieldType is the configured name (e.g. "containerImage", "ociArtifact").
	FieldType string `yaml:"fieldType"`
	// Raw is the unmodified string value found in the manifest.
	Raw string `yaml:"raw"`
	// Parsed components — empty strings mean the value was not present.
	Registry   string `yaml:"registry,omitempty"`
	Repository string `yaml:"repository,omitempty"`
	Tag        string `yaml:"tag,omitempty"`
	Digest     string `yaml:"digest,omitempty"`
	// Ref holds non-tag qualifiers like semver, digest, etc.
	Ref map[string]string `yaml:"ref,omitempty"`

	// Resolution is the ordered chain of resources traversed to find this artifact.
	// Index 0 is always the resource that directly contains the reference value.
	Resolution []ResolutionStep `yaml:"resolution"`

	// Warnings are non-fatal issues encountered while resolving this artifact.
	Warnings []string `yaml:"warnings,omitempty"`
}

// ResolutionStep records one hop in the reference chain.
type ResolutionStep struct {
	Kind      string `yaml:"kind"`
	Name      string `yaml:"name"`
	Namespace string `yaml:"namespace,omitempty"`
	File      string `yaml:"file,omitempty"`
	// Via is the field path that pointed to the next resource.
	Via string `yaml:"via,omitempty"`
	// Synthesized means this resource was not in any file; it was inferred.
	Synthesized bool `yaml:"synthesized,omitempty"`
	// Inline means this resource was nested inside a ResourceSet.
	Inline bool `yaml:"inline,omitempty"`
	// Input is the ResourceSet input that produced this resource.
	Input map[string]interface{} `yaml:"input,omitempty"`
}
