package registry

// Resource is a parsed Kubernetes resource with its raw fields and provenance.
type Resource struct {
	APIVersion string
	Kind       string
	Name       string
	Namespace  string
	Raw        map[string]interface{}

	// Source is the file this resource was loaded from (empty for synthetic resources).
	SourceFile string
	// KustomizeDir is the overlay directory whose kustomize build produced this resource.
	// Empty for resources loaded from plain files or created synthetically.
	KustomizeDir string
	// Inline is true when this resource was extracted from a ResourceSet.spec.resources list.
	Inline bool
	// Synthetic is true when this resource was generated by a Synthesizer rule.
	Synthetic bool
	// SyntheticFrom points to the resource that triggered synthesis.
	SyntheticFrom *ResourceRef
	// InputContext holds the ResourceSet input values used to materialize this resource.
	InputContext map[string]interface{}
}

// ResourceRef is a lightweight pointer to a resource by kind/namespace/name.
type ResourceRef struct {
	Kind      string
	Namespace string
	Name      string
	File      string
}

// Artifact is a discovered OCI reference with all its resolution sources.
type Artifact struct {
	// FieldType is the configured name (e.g. "containerImage", "ociArtifact").
	FieldType string `yaml:"fieldType" json:"fieldType"`
	// Reference is the canonical fully-qualified OCI reference (registry/repository:tag),
	// without any scheme prefix. Computed from the parsed Registry/Repository/Tag/Digest fields.
	Reference string `yaml:"reference" json:"reference"`
	// Parsed components — empty strings mean the value was not present.
	Registry   string `yaml:"registry,omitempty"   json:"registry,omitempty"`
	Repository string `yaml:"repository,omitempty" json:"repository,omitempty"`
	Tag        string `yaml:"tag,omitempty"        json:"tag,omitempty"`
	Digest     string `yaml:"digest,omitempty"     json:"digest,omitempty"`
	// Ref holds non-tag qualifiers like semver, digest, etc.
	Ref map[string]string `yaml:"ref,omitempty" json:"ref,omitempty"`

	// Sources lists every place this reference was found. Each entry holds the full
	// resolution chain for that occurrence (index 0 = first resolver hop, last = the
	// resource whose field directly contained the reference value). Multiple sources
	// occur when the same reference appears in independent manifests or chains.
	Sources []ArtifactSource `yaml:"sources" json:"sources"`

	// KustomizeOverlays lists the overlay directories (from kustomize build) that
	// produced this artifact. Multiple entries occur when different overlays render
	// the same ref. Empty for artifacts from plain files.
	KustomizeOverlays []string `yaml:"kustomizeOverlays,omitempty" json:"kustomizeOverlays,omitempty"`

	// Warnings are non-fatal issues encountered while resolving this artifact.
	Warnings []string `yaml:"warnings,omitempty" json:"warnings,omitempty"`
}

// ArtifactSource holds one resolution chain for an artifact.
// The named "chain" key avoids the `- -` double-dash YAML notation that would
// appear if [][]ResolutionStep were serialised directly.
type ArtifactSource struct {
	Chain []ResolutionStep `yaml:"chain" json:"chain"`
}

// ResolutionStep records one hop in the reference chain.
type ResolutionStep struct {
	Kind      string `yaml:"kind" json:"kind"`
	Name      string `yaml:"name" json:"name"`
	Namespace string `yaml:"namespace,omitempty" json:"namespace,omitempty"`
	File      string `yaml:"file,omitempty"      json:"file,omitempty"`
	// Via is the field path that pointed to the next resource.
	Via string `yaml:"via,omitempty" json:"via,omitempty"`
	// Raw is the literal field value extracted from this resource's YAML. Only set on the
	// terminal step (the resource whose field directly contained the reference value);
	// empty on intermediate resolver hops.
	Raw string `yaml:"raw,omitempty" json:"raw,omitempty"`
	// Synthesized means this resource was not in any file; it was inferred.
	Synthesized bool `yaml:"synthesized,omitempty" json:"synthesized,omitempty"`
	// Inline means this resource was nested inside a ResourceSet.
	Inline bool `yaml:"inline,omitempty" json:"inline,omitempty"`
	// Input is the ResourceSet input that produced this resource.
	Input map[string]interface{} `yaml:"input,omitempty" json:"input,omitempty"`
}

